CREATE TABLE Player (
	playerid INT NOT NULL PRIMARY KEY,
	name VARCHAR(20) NOT NULL,
	teamid INT,
	position VARCHAR(3),
	games_played INT
	);
	
CREATE TABLE Team (
	teamid INT NOT NULL PRIMARY KEY,
	name VARCHAR (3),
	games_played INT
	);

CREATE TABLE Season (
	seasonid INT,
	playerid INT
	);

CREATE TABLE Skaterstats (
   FK_playerid INT,
   season INT,
   --name VARCHAR (20),
   --team VARCHAR (3),
   --position VARCHAR (3),
   situation VARCHAR (5),
   icetime DECIMAL (5,3),
   shifts INT,
   gamescore DECIMAL (5,3),
   onice_xgoalspercentage DECIMAL (5,3),
   office_xgoalspercentage DECIMAL (5,3),
   onice_corsipercentage DECIMAL (5,3),
   office_corsipercentage DECIMAL (5,3),
   onice_fenwickpercentage DECIMAL (5,3),
   office_fenwickpercentage DECIMAL (5,3),
   icetimerank DECIMAL (5,3),
   i_f_xongoal DECIMAL (5,3),
   i_f_xgoals DECIMAL (5,3),
   i_f_xrebounds DECIMAL (5,3),
   i_f_xfreeze DECIMAL (5,3),
   i_f_xplaystopped DECIMAL (5,3),
   i_f_xplaycontinuedinzone DECIMAL (5,3),
   i_f_xplaycontinuedoutsidezone DECIMAL (5,3),
   i_f_flurryadjustedxgoals DECIMAL (5,3),
   i_f_scorevenueadjustedxgoals DECIMAL (5,3),
   i_f_flurryscorevenueadjustedxgoals DECIMAL (5,3),
   i_f_primaryassists DECIMAL (5,3),
   i_f_secondaryassists DECIMAL (5,3),
   i_f_shotsongoal DECIMAL (5,3),
   i_f_missedshots DECIMAL (5,3),
   i_f_blockedshotattempts DECIMAL (5,3),
   i_f_shotattempts DECIMAL (5,3),
   i_f_points DECIMAL (5,3),
   i_f_goals DECIMAL (5,3),
   i_f_rebounds DECIMAL (5,3),
   i_f_reboundgoals DECIMAL (5,3),
   i_f_freeze DECIMAL (5,3),
   i_f_playstopped DECIMAL (5,3),
   i_f_playcontinuedinzone DECIMAL (5,3),
   i_f_playcontinuedoutsidezone DECIMAL (5,3),
   i_f_savedshotsongoal DECIMAL (5,3),
   i_f_savedunblockedshotattempts DECIMAL (5,3),
   penalties DECIMAL (5,3),
   i_f_penalityminutes DECIMAL (5,3),
   i_f_faceoffswon DECIMAL (5,3),
   i_f_hits DECIMAL (5,3),
   i_f_takeaways DECIMAL (5,3),
   i_f_giveaways DECIMAL (5,3),
   i_f_lowdangershots DECIMAL (5,3),
   i_f_mediumdangershots DECIMAL (5,3),
   i_f_highdangershots DECIMAL (5,3),
   i_f_lowdangerxgoals DECIMAL (5,3),
   i_f_mediumdangerxgoals DESIMAL (5,3),
   i_f_highdangerxgoals DECIMAL (5,3),
   i_f_lowdangergoals DECIMAL (5,3),
   i_f_mediumdangergoals DECIMAL (5,3),
   i_f_highdangergoals DECIMAL (5,3),
   i_f_scoreadjustedshotsattempts DECIMAL (5,3),
   i_f_unblockedshotattempts DECIMAL (5,3),
   i_f_scoreadjustedunblockedshotattempts DECIMAL (5,3),
   i_f_dzonegiveaways DECIMAL (5,3),
   i_f_xgoalsfromxreboundsofshots DECIMAL (5,3),
   i_f_xgoalsfromactualreboundsofshots DECIMAL (5,3),
   i_f_reboundxgoals DECIMAL (5,3),
   i_f_xgoals_with_earned_rebounds DECIMAL (5,3),
   i_f_xgoals_with_earned_rebounds_scoreadjusted DECIMAL (5,3),
   i_f_xgoals_with_earned_rebounds_scoreflurryadjusted DECIMAL (5,3),
   i_f_shifts DECIMAL (5,3),
   i_f_ozoneshiftstarts DECIMAL (5,3),
   i_f_dzoneshiftstarts DECIMAL (5,3),
   i_f_neutralzoneshiftstarts DECIMAL (5,3),
   i_f_flyshiftstarts DECIMAL (5,3),
   i_f_ozoneshiftends DECIMAL (5,3),
   i_f_dzoneshiftends DECIMAL (5,3),
   i_f_neutralzoneshiftends DECIMAL (5,3),
   i_f_flyshiftends DECIMAL (5,3),
   faceoffswon DECIMAL (5,3),
   faceoffslost DECIMAL (5,3),
   timeonbench DECIMAL (5,3),
   penalityminutes DECIMAL (5,3),
   penalityminutesdrawn DECIMAL (5,3),
   penaltiesdrawn DECIMAL (5,3),
   shotsblockedbyplayer DECIMAL (5,3),
   onice_f_xongoal DECIMAL (5,3),
   onice_f_xgoals DECIMAL (5,3),
   onice_f_flurryadjustedxgoals DECIMAL (5,3),
   onice_f_scorevenueadjustedxgoals DECIMAL (5,3),
   onice_f_flurryscorevenueadjustedxgoals DECIMAL (5,3),
   onice_f_shotsongoal DECIMAL (5,3),
   onice_f_missedshots DECIMAL (5,3),
   onice_f_blockedshotattempts DECIMAL (5,3),
   onice_f_shotattempts DECIMAL (5,3),
   onice_f_goals DECIMAL (5,3),
   onice_f_rebounds DECIMAL (5,3),
   onice_f_reboundgoals DECIMAL (5,3),
   onice_f_lowdangershots DECIMAL (5,3),
   onice_f_mediumdangershots DECIMAL (5,3),
   onice_f_highdangershots DECIMAL (5,3),
   onice_f_lowdangerxgoals DECIMAL (5,3),
   onice_f_mediumdangerxgoals DECIMAL (5,3),
   onice_f_highdangerxgoals DECIMAL (5,3),
   onice_f_lowdangergoals DECIMAL (5,3),
   onice_f_mediumdangergoals DECIMAL (5,3),
   onice_f_highdangergoals DECIMAL (5,3),
   onice_f_scoreadjustedshotsattempts DECIMAL (5,3),
   onice_f_unblockedshotattempts DECIMAL (5,3),
   onice_f_scoreadjustedunblockedshotattempts DECIMAL (5,3),
   onice_f_xgoalsfromxreboundsofshots DECIMAL (5,3),
   onice_f_xgoalsfromactualreboundsofshots DECIMAL (5,3),
   onice_f_reboundxgoals DECIMAL (5,3),
   onice_f_xgoals_with_earned_rebounds DECIMAL (5,3),
   onice_f_xgoals_with_earned_rebounds_scoreadjusted DECIMAL (5,3),
   onice_f_xgoals_with_earned_rebounds_scoreflurryadjusted DECIMAL (5,3),
   onice_a_xongoal DECIMAL (5,3),
   onice_a_xgoals DECIMAL (5,3),
   onice_a_flurryadjustedxgoals DECIMAL (5,3),
   onice_a_scorevenueadjustedxgoals DECIMAL (5,3),
   onice_a_flurryscorevenueadjustedxgoals DECIMAL (5,3),
   onice_a_shotsongoal DECIMAL (5,3),
   onice_a_missedshots DECIMAL (5,3),
   onice_a_blockedshotattempts DECIMAL (5,3),
   onice_a_shotattempts DECIMAL (5,3),
   onice_a_goals DECIMAL (5,3),
   onice_a_rebounds DECIMAL (5,3),
   onice_a_reboundgoals DECIMAL (5,3),
   onice_a_lowdangershots DECIMAL (5,3),
   onice_a_mediumdangershots DECIMAL (5,3),
   onice_a_highdangershots DECIMAL (5,3),
   onice_a_lowdangerxgoals DECIMAL (5,3),
   onice_a_mediumdangerxgoals DECIMAL (5,3),
   onice_a_highdangerxgoals DECIMAL (5,3),
   onice_a_lowdangergoals DECIMAL (5,3),
   onice_a_mediumdangergoals DECIMAL (5,3),
   onice_a_highdangergoals DECIMAL (5,3),
   onice_a_scoreadjustedshotsattempts DECIMAL (5,3),
   onice_a_unblockedshotattempts DECIMAL (5,3),
   onice_a_scoreadjustedunblockedshotattempts DECIMAL (5,3),
   onice_a_xgoalsfromxreboundsofshots DECIMAL (5,3),
   onice_a_xgoalsfromactualreboundsofshots DECIMAL (5,3),
   onice_a_reboundxgoals DECIMAL (5,3),
   onice_a_xgoals_with_earned_rebounds DECIMAL (5,3),
   onice_a_xgoals_with_earned_rebounds_scoreadjusted DECIMAL (5,3),
   onice_a_xgoals_with_earned_rebounds_scoreflurryadjusted DECIMAL (5,3),
   office_f_xgoals DECIMAL (5,3),
   office_a_xgoals DECIMAL (5,3),
   office_f_shotattempts DECIMAL (5,3),
   office_a_shotattempts DECIMAL (5,3),
   xgoalsforaftershifts DECIMAL (5,3),
   xgoalsagainstaftershifts DECIMAL (5,3),
   corsiforaftershifts DECIMAL (5,3),
   corsiagainstaftershifts DECIMAL (5,3),
   fenwickforaftershifts DECIMAL (5,3),
   fenwickagainstaftershifts DECIMAL (5,3),
   FOREIGN KEY (FK_playerid) REFERENCES Player (playerid)
   );
  

CREATE TABLE Goaliestats ( 
   FK_playerid INT,
   season INT,
   --name VARCHAR (20),
   --team VARCHAR (3),
   --position VARCHAR (3),
   situation VARCHAR (5),
   --games_played INT,
   icetime DECIMAL (6,3),
   xgoals DECIMAL (6,3),
   goals DECIMAL (6,3),
   unblocked_shot_attempts DECIMAL (6,3),
   xrebounds DECIMAL (6,3),
   rebounds DECIMAL (6,3),
   xfreeze DECIMAL (6,3),
   freeze DECIMAL (6,3),
   xongoal DECIMAL (6,3),
   ongoal DECIMAL (6,3),
   xplaystopped DECIMAL (6,3),
   playstopped DECIMAL (6,3),
   xplaycontinuedinzone DECIMAL (6,3),
   playcontinuedinzone DECIMAL (6,3),
   xplaycontinuedoutsidezone DECIMAL (6,3),
   playcontinuedoutsidezone DECIMAL (6,3),
   flurryadjustedxgoals DECIMAL (6,3),
   lowdangershots DECIMAL (6,3),
   mediumdangershots DECIMAL (6,3),
   highdangershots DECIMAL (6,3),
   lowdangerxgoals DECIMAL (6,3),
   mediumdangerxgoals DECIMAL (6,3),
   highdangerxgoals DECIMAL (6,3),
   lowdangergoals DECIMAL (6,3),
   mediumdangergoals DECIMAL (6,3),
   highdangergoals DECIMAL (6,3),
   blocked_shot_attempts DECIMAL (6,3),
   penalityminutes DECIMAL (6,3),
   penalties DECIMAL (6,3)
);


CREATE TABLE Teamstats ( 
   team VARCHAR(3),
   season INT,
   name VARCHAR (3),
   team VARCHAR (3),
   --position DECIMAL (6,3),
   situation VARCHAR (5),
   --games_played INT,
   xgoalspercentage DECIMAL (6,3),
   corsipercentage DECIMAL (6,3),
   fenwickpercentage DECIMAL (6,3),
   icetime DECIMAL (6,3),
   xongoalfor DECIMAL (6,3),
   xgoalsfor DECIMAL (6,3),
   xreboundsfor DECIMAL (6,3),
   xfreezefor DECIMAL (6,3),
   xplaystoppedfor DECIMAL (6,3),
   xplaycontinuedinzonefor DECIMAL (6,3),
   xplaycontinuedoutsidezonefor DECIMAL (6,3),
   flurryadjustedxgoalsfor DECIMAL (6,3),
   scorevenueadjustedxgoalsfor DECIMAL (6,3),
   flurryscorevenueadjustedxgoalsfor DECIMAL (6,3),
   shotsongoalfor DECIMAL (6,3),
   missedshotsfor DECIMAL (6,3),
   blockedshotattemptsfor DECIMAL (6,3),
   shotattemptsfor DECIMAL (6,3),
   goalsfor DECIMAL (6,3),
   reboundsfor DECIMAL (6,3),
   reboundgoalsfor DECIMAL (6,3),
   freezefor DECIMAL (6,3),
   playstoppedfor DECIMAL (6,3),
   playcontinuedinzonefor DECIMAL (6,3),
   playcontinuedoutsidezonefor DECIMAL (6,3),
   savedshotsongoalfor DECIMAL (6,3),
   savedunblockedshotattemptsfor DECIMAL (6,3),
   penaltiesfor DECIMAL (6,3),
   penalityminutesfor DECIMAL (6,3),
   faceoffswonfor DECIMAL (6,3),
   hitsfor DECIMAL (6,3),
   takeawaysfor DECIMAL (6,3),
   giveawaysfor DECIMAL (6,3),
   lowdangershotsfor DECIMAL (6,3),
   mediumdangershotsfor DECIMAL (6,3),
   highdangershotsfor DECIMAL (6,3),
   lowdangerxgoalsfor DECIMAL (6,3),
   mediumdangerxgoalsfor DECIMAL (6,3),
   highdangerxgoalsfor DECIMAL (6,3),
   lowdangergoalsfor DECIMAL (6,3),
   mediumdangergoalsfor DECIMAL (6,3),
   highdangergoalsfor DECIMAL (6,3),
   scoreadjustedshotsattemptsfor DECIMAL (6,3),
   unblockedshotattemptsfor DECIMAL (6,3),
   scoreadjustedunblockedshotattemptsfor DECIMAL (6,3),
   dzonegiveawaysfor DECIMAL (6,3),
   xgoalsfromxreboundsofshotsfor DECIMAL (6,3),
   xgoalsfromactualreboundsofshotsfor DECIMAL (6,3),
   reboundxgoalsfor DECIMAL (6,3),
   totalshotcreditfor DECIMAL (6,3),
   scoreadjustedtotalshotcreditfor DECIMAL (6,3),
   scoreflurryadjustedtotalshotcreditfor DECIMAL (6,3),
   xongoalagainst DECIMAL (6,3),
   xgoalsagainst DECIMAL (6,3),
   xreboundsagainst DECIMAL (6,3),
   xfreezeagainst DECIMAL (6,3),
   xplaystoppedagainst DECIMAL (6,3),
   xplaycontinuedinzoneagainst DECIMAL (6,3),
   xplaycontinuedoutsidezoneagainst DECIMAL (6,3),
   flurryadjustedxgoalsagainst DECIMAL (6,3),
   scorevenueadjustedxgoalsagainst DECIMAL (6,3),
   flurryscorevenueadjustedxgoalsagainst DECIMAL (6,3),
   shotsongoalagainst DECIMAL (6,3),
   missedshotsagainst DECIMAL (6,3),
   blockedshotattemptsagainst DECIMAL (6,3),
   shotattemptsagainst DECIMAL (6,3),
   goalsagainst DECIMAL (6,3),
   reboundsagainst DECIMAL (6,3),
   reboundgoalsagainst DECIMAL (6,3),
   freezeagainst DECIMAL (6,3),
   playstoppedagainst DECIMAL (6,3),
   playcontinuedinzoneagainst DECIMAL (6,3),
   playcontinuedoutsidezoneagainst DECIMAL (6,3),
   savedshotsongoalagainst DECIMAL (6,3),
   savedunblockedshotattemptsagainst DECIMAL (6,3),
   penaltiesagainst DECIMAL (6,3),
   penalityminutesagainst DECIMAL (6,3),
   faceoffswonagainst DECIMAL (6,3),
   hitsagainst DECIMAL (6,3),
   takeawaysagainst DECIMAL (6,3),
   giveawaysagainst DECIMAL (6,3),
   lowdangershotsagainst DECIMAL (6,3),
   mediumdangershotsagainst DECIMAL (6,3),
   highdangershotsagainst DECIMAL (6,3),
   lowdangerxgoalsagainst DECIMAL (6,3),
   mediumdangerxgoalsagainst DECIMAL (6,3),
   highdangerxgoalsagainst DECIMAL (6,3),
   lowdangergoalsagainst DECIMAL (6,3),
   mediumdangergoalsagainst DECIMAL (6,3),
   highdangergoalsagainst DECIMAL (6,3),
   scoreadjustedshotsattemptsagainst DECIMAL (6,3),
   unblockedshotattemptsagainst DECIMAL (6,3),
   scoreadjustedunblockedshotattemptsagainst DECIMAL (6,3),
   dzonegiveawaysagainst DECIMAL (6,3),
   xgoalsfromxreboundsofshotsagainst DECIMAL (6,3),
   xgoalsfromactualreboundsofshotsagainst DECIMAL (6,3),
   reboundxgoalsagainst DECIMAL (6,3),
   totalshotcreditagainst DECIMAL (6,3),
   scoreadjustedtotalshotcreditagainst DECIMAL (6,3),
   scoreflurryadjustedtotalshotcreditagainst DECIMAL (6,3)
);
